# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 611459da4f6c2b6056e8cae21f6d401a2d3f27537e1316615c00be69d718ea37f1fa4a0a923358ac0583174f72018a2030ac5be0b44da7a66ca0a148b6cde09b

test:
  secret_key_base: 4f3bc8dfc39af377b06e7c7ca0b84fd59ad41622a63f6bc1f2cb79e620a5dfb314cbb7da23dfc671074e1b7012e72a0c30418d22cb01c88d89ce3865d3848273

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
